### ISSUE TITLE
Running outside of the sbt REPL

### ISSUE THREAD

**Issue by ps0uth** [nasa-jpl-cord-19/covid19-knowledge-graph#3]
In the README.md file you give the following instructions to process the input json files.

```
## Running

Launch sbt:

    $ sbt

Run the program with an argument indicating the input `data` directory containing the dataset:

    > run path/to/data/containing/Commercial use subset json files
```

This is not conducive to running in an automated pipeline, is there any way we can get an assembly build task so that processing can be run like

```bash
$ java -jar covid19-knowledge-graph.jar path/to/data/containing/commercial_use_subset_json_files
```

**Comment by lewismc** [comment]
This addressed in master branch, please see https://github.com/nasa-jpl-cord-19/covid19-knowledge-graph#as-a-standalone-jar
